server:           # Настраиваем сервер
  port: 8180
  servlet:
    context-path: /webcloudfile
spring:           # Настраиваем hibernate
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        temp:
          use_jdbc_metadata_defaults: false
  datasource:     # Подключение к базе postgres - webcloudfile
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=webcloudfile
    username: postgres
    password: postgres

